---
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $discoveryUri: '%env(string:OPEN_ID_DISCOVERY_URL)%'

    RZ\Roadiz\CompatBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Event/'

    RZ\Roadiz\OpenId\:
        resource: '%kernel.project_dir%/vendor/roadiz/openid/src/'
        autowire: true
        autoconfigure: true
        exclude:
            - '%kernel.project_dir%/vendor/roadiz/openid/src/OpenIdServiceProvider.php'

    # Explicit declaration
    RZ\Roadiz\CompatBundle\Controller\AppController:
    RZ\Roadiz\CompatBundle\Controller\Controller:
    RZ\Roadiz\CompatBundle\Controller\FrontendController:

    # These types need to be aliases early for FormPass
    # because their need constructor injection
    RZ\Roadiz\CMS\Forms\DocumentCollectionType:
        alias: RZ\Roadiz\CoreBundle\Form\DocumentCollectionType
    RZ\Roadiz\CMS\Forms\GroupsType:
        alias: RZ\Roadiz\CoreBundle\Form\GroupsType
    RZ\Roadiz\CMS\Forms\NodeTypesType:
        alias: RZ\Roadiz\CoreBundle\Form\NodeTypesType
    RZ\Roadiz\CMS\Forms\NodesType:
        alias: RZ\Roadiz\CoreBundle\Form\NodesType
    RZ\Roadiz\CMS\Forms\RolesType:
        alias: RZ\Roadiz\CoreBundle\Form\RolesType
    RZ\Roadiz\CMS\Forms\SettingDocumentType:
        alias: RZ\Roadiz\CoreBundle\Form\SettingDocumentType
    RZ\Roadiz\CMS\Forms\SettingGroupType:
        alias: RZ\Roadiz\CoreBundle\Form\SettingGroupType
    RZ\Roadiz\CMS\Forms\SettingType:
        alias: RZ\Roadiz\CoreBundle\Form\SettingType
    RZ\Roadiz\CMS\Forms\TagTranslationDocumentType:
        alias: RZ\Roadiz\CoreBundle\Form\TagTranslationDocumentType
    RZ\Roadiz\CMS\Forms\TranslationsType:
        alias: RZ\Roadiz\CoreBundle\Form\TranslationsType
    RZ\Roadiz\CMS\Forms\UrlAliasType:
        alias: RZ\Roadiz\CoreBundle\Form\UrlAliasType
    RZ\Roadiz\CMS\Forms\UsersType:
        alias: RZ\Roadiz\CoreBundle\Form\UsersType

    securityTokenStorage:
        alias: security.token_storage
        public: true
    Pimple\Container:
        alias: Psr\Container\ContainerInterface
        public: true
    factory.handler:
        alias: RZ\Roadiz\CoreBundle\EntityHandler\HandlerFactory
        public: true
    settingsBag:
        alias: RZ\Roadiz\CoreBundle\Bag\Settings
        public: true
    nodeTypesBag:
        alias: RZ\Roadiz\CoreBundle\Bag\NodeTypes
        public: true
    rolesBag:
        alias: RZ\Roadiz\CoreBundle\Bag\Roles
        public: true
    formFactory:
        alias: 'form.factory'
        public: true
    dispatcher:
        alias: 'event_dispatcher'
        public: true
    Symfony\Component\HttpFoundation\ParameterBag:
        alias: RZ\Roadiz\CoreBundle\Bag\Settings
    Doctrine\Common\Cache\CacheProvider:
        alias: 'doctrine.orm.cache.provider.cache.doctrine.orm.default.metadata'
    nodesSourcesUrlCacheProvider:
        alias: 'doctrine.orm.cache.provider.cache.doctrine.orm.default.metadata'
        public: true
    securityAuthenticationUtils:
        alias: Symfony\Component\Security\Http\Authentication\AuthenticationUtils
        public: true
    entityManager:
        public: true
        alias: 'doctrine.orm.default_entity_manager'
    em:
        public: true
        alias: 'doctrine.orm.default_entity_manager'


