---
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $discoveryUri: '%env(string:OPEN_ID_DISCOVERY_URL)%'

    RZ\Roadiz\CompatBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Event/'

    RZ\Roadiz\OpenId\:
        resource: '%kernel.project_dir%/vendor/roadiz/openid/src/'
        autowire: true
        autoconfigure: true
        exclude:
            - '%kernel.project_dir%/vendor/roadiz/openid/src/OpenIdServiceProvider.php'

    securityTokenStorage:
        alias: security.token_storage
        public: true
    Pimple\Container:
        alias: Psr\Container\ContainerInterface
        public: true
    factory.handler:
        alias: RZ\Roadiz\CoreBundle\EntityHandler\HandlerFactory
        public: true
    settingsBag:
        alias: RZ\Roadiz\CoreBundle\Bag\Settings
        public: true
    nodeTypesBag:
        alias: RZ\Roadiz\CoreBundle\Bag\NodeTypes
        public: true
    rolesBag:
        alias: RZ\Roadiz\CoreBundle\Bag\Roles
        public: true
    formFactory:
        alias: 'form.factory'
        public: true
    dispatcher:
        alias: 'event_dispatcher'
        public: true
    Symfony\Component\HttpFoundation\ParameterBag:
        alias: RZ\Roadiz\CoreBundle\Bag\Settings
    Doctrine\Common\Cache\CacheProvider:
        alias: 'doctrine.orm.cache.provider.cache.doctrine.orm.default.metadata'
    nodesSourcesUrlCacheProvider:
        alias: 'doctrine.orm.cache.provider.cache.doctrine.orm.default.metadata'
        public: true
    securityAuthenticationUtils:
        alias: Symfony\Component\Security\Http\Authentication\AuthenticationUtils
        public: true
    entityManager:
        public: true
        alias: 'doctrine.orm.default_entity_manager'
    em:
        public: true
        alias: 'doctrine.orm.default_entity_manager'


