---
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $publicDir: '%kernel.project_dir%/public'
            $cacheDir: '%kernel.project_dir%/var/cache'
            $projectDir: '%kernel.project_dir%'
            $debug: '%kernel.debug%'

    RZ\Roadiz\CompatBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Event/'

    #
    # Automatic themes registration
    #
    Themes\:
        resource: '%kernel.project_dir%/themes/'
        autowire: true
        autoconfigure: true
        exclude:
            - '%kernel.project_dir%/themes/DependencyInjection/'
            - '%kernel.project_dir%/themes/app/'
            - '%kernel.project_dir%/themes/public/'
            - '%kernel.project_dir%/themes/Resources/'
            - '%kernel.project_dir%/themes/Services/'
            - '%kernel.project_dir%/themes/static/'
            - '%kernel.project_dir%/themes/Entity/'
            - '%kernel.project_dir%/themes/Kernel.php'
            - '%kernel.project_dir%/themes/Tests/'

    # Explicit declaration
    RZ\Roadiz\CompatBundle\Controller\AppController: ~
    RZ\Roadiz\CompatBundle\Controller\Controller: ~
    RZ\Roadiz\CompatBundle\Controller\FrontendController: ~

    RZ\Roadiz\Attribute\Form\AttributeDocumentType: ~
    RZ\Roadiz\Attribute\Form\AttributeGroupTranslationType: ~
    RZ\Roadiz\Attribute\Form\AttributeGroupsType: ~
    RZ\Roadiz\Attribute\Form\AttributeGroupType: ~
    RZ\Roadiz\Attribute\Form\AttributeTranslationType: ~
    RZ\Roadiz\Attribute\Form\AttributeType: ~
    RZ\Roadiz\Attribute\Form\AttributeValueTranslationType: ~
    RZ\Roadiz\Attribute\Form\AttributeValueType: ~
    RZ\Roadiz\CMS\Forms\ColorType: ~
    RZ\Roadiz\CMS\Forms\CompareDateType: ~
    RZ\Roadiz\CMS\Forms\CompareDatetimeType: ~
    RZ\Roadiz\CMS\Forms\Constraints\HexadecimalColor: ~
    RZ\Roadiz\CMS\Forms\Constraints\HexadecimalColorValidator: ~
    RZ\Roadiz\CMS\Forms\Constraints\NodeTypeField: ~
    RZ\Roadiz\CMS\Forms\Constraints\NodeTypeFieldValidator: ~
    RZ\Roadiz\CMS\Forms\Constraints\NonSqlReservedWord: ~
    RZ\Roadiz\CMS\Forms\Constraints\NonSqlReservedWordValidator: ~
    RZ\Roadiz\CMS\Forms\Constraints\Recaptcha: ~
    RZ\Roadiz\CMS\Forms\Constraints\RecaptchaValidator: ~
    RZ\Roadiz\CMS\Forms\Constraints\SimpleLatinString: ~
    RZ\Roadiz\CMS\Forms\Constraints\SimpleLatinStringValidator: ~
    RZ\Roadiz\CMS\Forms\Constraints\UniqueEntity: ~
    RZ\Roadiz\CMS\Forms\Constraints\UniqueEntityValidator: ~
    RZ\Roadiz\CMS\Forms\Constraints\UniqueFilename: ~
    RZ\Roadiz\CMS\Forms\Constraints\UniqueFilenameValidator: ~
    RZ\Roadiz\CMS\Forms\Constraints\UniqueNodeName: ~
    RZ\Roadiz\CMS\Forms\Constraints\UniqueNodeNameValidator: ~
    RZ\Roadiz\CMS\Forms\Constraints\UniqueTagName: ~
    RZ\Roadiz\CMS\Forms\Constraints\UniqueTagNameValidator: ~
    RZ\Roadiz\CMS\Forms\Constraints\ValidAccountConfirmationToken: ~
    RZ\Roadiz\CMS\Forms\Constraints\ValidAccountConfirmationTokenValidator: ~
    RZ\Roadiz\CMS\Forms\Constraints\ValidAccountEmail: ~
    RZ\Roadiz\CMS\Forms\Constraints\ValidAccountEmailValidator: ~
    RZ\Roadiz\CMS\Forms\Constraints\ValidFacebookName: ~
    RZ\Roadiz\CMS\Forms\Constraints\ValidFacebookNameValidator: ~
    RZ\Roadiz\CMS\Forms\Constraints\ValidYaml: ~
    RZ\Roadiz\CMS\Forms\Constraints\ValidYamlValidator: ~
    RZ\Roadiz\CMS\Forms\CreatePasswordType: ~
    RZ\Roadiz\CMS\Forms\CssType: ~
    RZ\Roadiz\CMS\Forms\CustomFormsType: ~
    RZ\Roadiz\CMS\Forms\DataTransformer\DocumentCollectionTransformer: ~
    RZ\Roadiz\CMS\Forms\DataTransformer\EntityCollectionTransformer: ~
    RZ\Roadiz\CMS\Forms\DataTransformer\ExplorerProviderItemTransformer: ~
    RZ\Roadiz\CMS\Forms\DataTransformer\FolderCollectionTransformer: ~
    RZ\Roadiz\CMS\Forms\DataTransformer\JoinDataTransformer: ~
    RZ\Roadiz\CMS\Forms\DataTransformer\NodeTypeTransformer: ~
    RZ\Roadiz\CMS\Forms\DataTransformer\PersistableTransformer: ~
    RZ\Roadiz\CMS\Forms\DataTransformer\ProviderDataTransformer: ~
    RZ\Roadiz\CMS\Forms\DataTransformer\ReversePersistableTransformer: ~
    RZ\Roadiz\CMS\Forms\DataTransformer\TagTranslationDocumentsTransformer: ~
    RZ\Roadiz\CMS\Forms\DataTransformer\TranslationTransformer: ~
    RZ\Roadiz\CMS\Forms\DocumentCollectionType: ~
    RZ\Roadiz\CMS\Forms\EnumerationType: ~
    RZ\Roadiz\CMS\Forms\ExplorerProviderItemType: ~
    RZ\Roadiz\CMS\Forms\ExtendedBooleanType: ~
    RZ\Roadiz\CMS\Forms\FontVariantsType: ~
    RZ\Roadiz\CMS\Forms\GroupsType: ~
    RZ\Roadiz\CMS\Forms\HoneypotType: ~
    RZ\Roadiz\CMS\Forms\JsonType: ~
    RZ\Roadiz\CMS\Forms\LoginRequestForm: ~
    RZ\Roadiz\CMS\Forms\LoginResetForm: ~
    RZ\Roadiz\CMS\Forms\MarkdownType: ~
    RZ\Roadiz\CMS\Forms\MultipleEnumerationType: ~
    RZ\Roadiz\CMS\Forms\NodeStatesType: ~
    RZ\Roadiz\CMS\Forms\NodeTypesType: ~
    RZ\Roadiz\CMS\Forms\NodesType: ~
    RZ\Roadiz\CMS\Forms\RecaptchaType: ~
    RZ\Roadiz\CMS\Forms\RolesType: ~
    RZ\Roadiz\CMS\Forms\SeparatorType: ~
    RZ\Roadiz\CMS\Forms\SettingDocumentType: ~
    RZ\Roadiz\CMS\Forms\SettingGroupType: ~
    RZ\Roadiz\CMS\Forms\SettingType: ~
    RZ\Roadiz\CMS\Forms\SettingTypeResolver: ~
    RZ\Roadiz\CMS\Forms\TagTranslationDocumentType: ~
    RZ\Roadiz\CMS\Forms\TagsType: ~
    RZ\Roadiz\CMS\Forms\ThemesType: ~
    RZ\Roadiz\CMS\Forms\TranslationsType: ~
    RZ\Roadiz\CMS\Forms\UrlAliasType: ~
    RZ\Roadiz\CMS\Forms\UsersType: ~
    RZ\Roadiz\CMS\Forms\YamlType: ~
    RZ\Roadiz\Webhook\Form\WebhookType: ~

    securityTokenStorage:
        alias: security.token_storage
        public: true
    factory.handler:
        alias: RZ\Roadiz\CoreBundle\EntityHandler\HandlerFactory
        public: true
    settingsBag:
        alias: RZ\Roadiz\CoreBundle\Bag\Settings
        public: true
    nodeTypesBag:
        alias: RZ\Roadiz\CoreBundle\Bag\NodeTypes
        public: true
    rolesBag:
        alias: RZ\Roadiz\CoreBundle\Bag\Roles
        public: true
    assetPackages:
        alias: RZ\Roadiz\Utils\Asset\Packages
        public: true
    Symfony\Contracts\Translation\TranslatorInterface:
        alias: 'translator.default'
        public: true
    formFactory:
        alias: 'form.factory'
        public: true
    csrfTokenManager:
        alias: 'security.csrf.token_manager'
        public: true
    dispatcher:
        alias: 'event_dispatcher'
        public: true
    logger:
        alias: 'monolog.logger'
        public: true
    Symfony\Component\HttpFoundation\ParameterBag:
        alias: RZ\Roadiz\CoreBundle\Bag\Settings
    securityAuthenticationUtils:
        alias: Symfony\Component\Security\Http\Authentication\AuthenticationUtils
        public: true
    entityManager:
        public: true
        alias: 'doctrine.orm.default_entity_manager'
    em:
        public: true
        alias: 'doctrine.orm.default_entity_manager'

    #
    # Themes aware stuff
    #
    roadiz_compat.twig_loader:
        class: Twig\Loader\FilesystemLoader
        tags: ['twig.loader']
    RZ\Roadiz\CompatBundle\Routing\ThemeRoutesLoader:
        tags: [ routing.loader ]

    #
    # Made routers theme aware
    #
    RZ\Roadiz\CompatBundle\Routing\ThemeAwareNodeUrlMatcher:
        decorates: RZ\Roadiz\CoreBundle\Routing\NodeUrlMatcher
        arguments:
            - '@RZ\Roadiz\CompatBundle\Theme\ThemeResolverInterface'
            - '@.inner'
    RZ\Roadiz\CompatBundle\Routing\ThemeAwareNodeRouter:
        decorates: RZ\Roadiz\CoreBundle\Routing\NodeRouter
        arguments:
            - '@RZ\Roadiz\CompatBundle\Theme\ThemeResolverInterface'
            - '@.inner'

    RZ\Roadiz\CompatBundle\EventSubscriber\MaintenanceModeSubscriber:
        arguments:
            - '@RZ\Roadiz\CoreBundle\Bag\Settings'
            - '@security.helper'
            - '@RZ\Roadiz\CompatBundle\Theme\ThemeResolverInterface'
            - '@service_container'
    RZ\Roadiz\CompatBundle\EventSubscriber\ExceptionSubscriber:
        arguments:
            - '@RZ\Roadiz\CompatBundle\Theme\ThemeResolverInterface'
            - '@RZ\Roadiz\CoreBundle\Exception\ExceptionViewer'
            - '@service_container'
